import { Store, LandingSection, LandingPageData } from '../src/types';

export const INITIAL_STORE: Store = {
  id: 'store-dzprint-default',
  owner_id: 'owner-master-algeria',
  slug: 'dzprint',
  name: 'ديزاد برينت | DZPrint',
  logo: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=300&auto=format&fit=crop&q=80',
  favicon: '/favicon.ico',
  phone: '0550 12 34 56',
  whatsapp: '0550 12 34 56',
  email: 'contact@dzprint.dz',
  address: 'الجزائر العاصمة، بئر مراد رايس',
  description: 'المنصة الأولى للطباعة الرقمية المباشرة DTF والشحن لـ 58 ولاية في الجزائر',
  default_language: 'ar',
  supported_languages: ['ar', 'fr', 'en'],
  created_at: '2026-01-01T00:00:00.000Z',
  updated_at: '2026-03-01T00:00:00.000Z',
};

export const INITIAL_LANDING_SECTIONS: LandingSection[] = [
  {
    id: 'sec-hero',
    store_id: 'store-dzprint-default',
    type: 'hero',
    sort_order: 1,
    is_visible: true,
    content: {
      title_ar: 'اطبع تصاميمك المخصصة على أجود الملابس والمجات في الجزائر',
      title_fr: 'Imprimez vos créations sur des vêtements & mugs haut de gamme en Algérie',
      title_en: 'Print Your Custom Designs on Premium Apparel & Mugs in Algeria',
      subtitle_ar: 'طباعة DTF رقمية فائقة الدقة وثابتة مع الغسيل. اختر من تصاميمنا الفنية أو ارفع تصميمك الخاص مع الدفع عند الاستلام والتوصيل لـ 58 ولاية.',
      subtitle_fr: 'Impression textile DTF ultra HD et résistante aux lavages. Choisissez parmi notre catalogue ou importez votre propre design.',
      subtitle_en: 'Ultra HD DTF printing built to last. Pick from curated artistic designs or upload your own artwork with Cash on Delivery in 58 wilayas.',
      badge_ar: '🇩🇿 الورشة رقم 1 للطباعة الرقمية المباشرة في الجزائر',
      badge_fr: '🇩🇿 Atelier N°1 d Impression DTF en Algérie',
      badge_en: '🇩🇿 Algeria #1 Direct-to-Film Printing Workshop',
      btn_text_ar: 'ابدأ تصميم منتجك الآن',
      btn_text_fr: 'Personnaliser un produit',
      btn_text_en: 'Start Customizing Now',
      btn_link: '#custom-design',
      secondary_btn_text_ar: 'تصفح المتجر والمنتجات',
      secondary_btn_text_fr: 'Explorer la boutique',
      secondary_btn_text_en: 'Explore Products',
      secondary_btn_link: '#shop',
      image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=1000&auto=format&fit=crop&q=80',
    },
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'sec-services',
    store_id: 'store-dzprint-default',
    type: 'services',
    sort_order: 2,
    is_visible: true,
    content: {
      title_ar: 'لماذا يختار آلاف الجزائريين متجر ديزاد برينت؟',
      title_fr: 'Pourquoi des milliers d Algériens choisissent DZPrint ?',
      title_en: 'Why Thousands of Algerians Choose DZPrint?',
      subtitle_ar: 'نقدم لك أفضل تجربة طباعة مخصصة بأعلى معايير الجودة العالمية والسرعة الفائقة',
      subtitle_fr: 'Nous vous offrons la meilleure qualité d impression personnalisée aux normes internationales',
      subtitle_en: 'We provide top-grade custom printing meeting international quality standards and fast fulfillment',
      items: [
        {
          icon: 'Truck',
          title_ar: 'توصيل سريع لـ 58 ولاية',
          title_fr: 'Livraison express 58 wilayas',
          title_en: 'Fast Shipping in 58 Wilayas',
          desc_ar: 'توصيل للمنزل أو للمكتب عبر يالادين وزر إكسبريس والمكتب',
          desc_fr: 'À domicile ou en point relais via Yalidine & ZR Express',
          desc_en: 'Home delivery or agency pickup with Yalidine & ZR Express',
        },
        {
          icon: 'ShieldCheck',
          title_ar: 'قطن طبيعي 100% ممتاز',
          title_fr: '100% Coton Supérieur',
          title_en: '100% Premium Cotton',
          desc_ar: 'أقمشة قطنية ممشطة فاخرة أوزان 240غ و380غ مريحة وتدوم طويلاً',
          desc_fr: 'Tissus en coton peigné 240g et 380g doux et durables',
          desc_en: 'Heavy combed cotton 240g & 380g breathable and durable',
        },
        {
          icon: 'Printer',
          title_ar: 'طباعة DTF فائقة الوضوح',
          title_fr: 'Impression DTF Ultra HD',
          title_en: 'Ultra HD DTF Printing',
          desc_ar: 'ألوان ساطعة زاهية لا تبهت ولا تتشقق مع تكرار الغسيل الآلي',
          desc_fr: 'Couleurs vibrantes qui résistent à des dizaines de lavages',
          desc_en: 'Vibrant colors that resist cracking through dozens of washes',
        },
        {
          icon: 'CreditCard',
          title_ar: 'الدفع نقداً عند الاستلام',
          title_fr: 'Paiement à la livraison (COD)',
          title_en: 'Cash on Delivery Guaranteed',
          desc_ar: 'افحص طلبك وادفع بأمان تام لمندوب التوصيل بعد المعاينة',
          desc_fr: 'Inspectez votre colis et payez en toute sécurité à la réception',
          desc_en: 'Inspect your parcel and pay securely upon arrival at your doorstep',
        },
      ],
    },
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'sec-categories',
    store_id: 'store-dzprint-default',
    type: 'categories',
    sort_order: 3,
    is_visible: true,
    content: {
      title_ar: 'تشكيلة المنتجات الجاهزة للطباعة والتخصيص',
      title_fr: 'Notre Gamme de Produits Personnalisables',
      title_en: 'Our Range of Customizable Products',
      subtitle_ar: 'اختر الصنف المناسب لك وابدأ بوضع تصميمك أو كتابتك عليه مباشرة',
      subtitle_fr: 'Sélectionnez votre produit et commencez à le personnaliser instantanément',
      subtitle_en: 'Select your preferred product and start placing your visual or text directly',
    },
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'sec-featured',
    store_id: 'store-dzprint-default',
    type: 'featured_products',
    sort_order: 4,
    is_visible: true,
    content: {
      title_ar: 'المنتجات الأكثر طلباً ومبيعاً',
      title_fr: 'Nos Meilleures Ventes',
      title_en: 'Best Selling & Trending Apparel',
      subtitle_ar: 'منتجات نالت إعجاب ورضا مئات الزبائن في الجزائر بفضل متانتها وفخامتها',
      subtitle_fr: 'Les articles les plus plébiscités par nos clients à travers l Algérie',
      subtitle_en: 'Top choices praised by hundreds of happy customers across Algeria',
      max_items: 6,
    },
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'sec-promo',
    store_id: 'store-dzprint-default',
    type: 'promo_banner',
    sort_order: 5,
    is_visible: true,
    content: {
      title_ar: 'تخفيض خاص 10% على طلبيتك الأولى!',
      title_fr: 'Réduction spéciale de 10% sur votre 1ère commande !',
      title_en: 'Special 10% Discount on Your First Order!',
      subtitle_ar: 'استخدم الرمز الترويجي DZPRINT10 عند إتمام الدفع واستفد من الخصم المباشر',
      subtitle_fr: 'Utilisez le code promo DZPRINT10 lors de la validation de votre panier',
      subtitle_en: 'Use promo code DZPRINT10 at checkout to claim your instant discount',
      discount_code: 'DZPRINT10',
      discount_percent: 10,
      btn_text_ar: 'تسوق واستخدم الكوبون',
      btn_text_fr: 'Profiter de l offre',
      btn_text_en: 'Shop & Claim Promo',
      btn_link: '#shop',
    },
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'sec-about',
    store_id: 'store-dzprint-default',
    type: 'about',
    sort_order: 6,
    is_visible: true,
    content: {
      title_ar: 'قصة ورشة ديزاد برينت الجزائرية',
      title_fr: 'L Histoire de l Atelier DZPrint Algérie',
      title_en: 'The Story of DZPrint Algerian Workshop',
      subtitle_ar: 'من قلب العاصمة، نجمع بين الحرفية الجزائرية وأحدث تقنيات الطباعة العالمية',
      subtitle_fr: 'Au cœur d Alger, nous allions savoir-faire artisanal et technologie numérique de pointe',
      subtitle_en: 'In the heart of Algiers, blending authentic Algerian craftsmanship with modern industrial printing',
      image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    },
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'sec-testimonials',
    store_id: 'store-dzprint-default',
    type: 'testimonials',
    sort_order: 7,
    is_visible: true,
    content: {
      title_ar: 'ماذا يقول عملاؤنا في مختلف الولايات؟',
      title_fr: 'Ce que disent nos clients dans toute l Algérie',
      title_en: 'What Our Customers Across Algeria Say',
      subtitle_ar: 'تقييمات حقيقية من زبائن استلموا طلبياتهم وجربوا جودة الطباعة والأقمشة',
      subtitle_fr: 'Avis vérifiés de clients ayant testé la tenue et la douceur de nos textiles',
      subtitle_en: 'Real feedback from customers who experienced our print durability and fabric quality',
    },
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'sec-faq',
    store_id: 'store-dzprint-default',
    type: 'faq',
    sort_order: 8,
    is_visible: true,
    content: {
      title_ar: 'الأسئلة الأكثر تداولاً وإجاباتها',
      title_fr: 'Questions Fréquemment Posées',
      title_en: 'Frequently Asked Questions',
      subtitle_ar: 'كل ما تحتاج معرفته حول المقاسات، سرعة التوصيل، والعناية بالملابس المطبوعة',
      subtitle_fr: 'Tout ce que vous devez savoir sur nos délais, nos tailles et l entretien',
      subtitle_en: 'Everything you need to know about sizing, delivery times, and garment care',
    },
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'sec-contact',
    store_id: 'store-dzprint-default',
    type: 'contact',
    sort_order: 9,
    is_visible: true,
    content: {
      title_ar: 'تواصل معنا واستفسر عن طلبيات الجملة والشركات',
      title_fr: 'Contactez-nous pour vos projets & commandes groupées',
      title_en: 'Contact Us for Inquiries & Corporate Bulk Orders',
      subtitle_ar: 'فريق الدعم الفني جاهز للرد على استفساراتك هاتفياً أو عبر واتساب طوال أيام الأسبوع',
      subtitle_fr: 'Notre équipe est à votre disposition par téléphone et WhatsApp 7j/7',
      subtitle_en: 'Our support team is ready on WhatsApp and phone throughout the week',
    },
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'sec-cta',
    store_id: 'store-dzprint-default',
    type: 'cta',
    sort_order: 10,
    is_visible: true,
    content: {
      title_ar: 'جاهز لطباعة فكرتك المميزة وتجربة الجودة؟',
      title_fr: 'Prêt à donner vie à votre création ?',
      title_en: 'Ready to Bring Your Custom Idea to Life?',
      subtitle_ar: 'صمم في دقائق، أكّد طلبك، واستلم منتجك حتى باب منزلك مع الدفع عند الاستلام',
      subtitle_fr: 'Créez en quelques clics, recevez votre colis à domicile et payez à la livraison',
      subtitle_en: 'Design in minutes, confirm by phone, and get delivery straight to your door',
      btn_text_ar: 'ابدأ التخصيص الفوري',
      btn_text_fr: 'Créer mon design',
      btn_text_en: 'Start Customizing Now',
      btn_link: '#custom-design',
    },
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-03-01T00:00:00.000Z',
  },
];

export const INITIAL_LANDING_PAGE: LandingPageData = {
  store_id: 'store-dzprint-default',
  draft_sections: JSON.parse(JSON.stringify(INITIAL_LANDING_SECTIONS)),
  published_sections: JSON.parse(JSON.stringify(INITIAL_LANDING_SECTIONS)),
  published_at: '2026-01-01T00:00:00.000Z',
  updated_at: '2026-03-01T00:00:00.000Z',
};
